#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cicek3
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FLUERİSTE")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUrunler(Urunler instance);
    partial void UpdateUrunler(Urunler instance);
    partial void DeleteUrunler(Urunler instance);
    partial void InsertKategori(Kategori instance);
    partial void UpdateKategori(Kategori instance);
    partial void DeleteKategori(Kategori instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FLUERİSTEConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Urunler> Urunlers
		{
			get
			{
				return this.GetTable<Urunler>();
			}
		}
		
		public System.Data.Linq.Table<Kategori> Kategoris
		{
			get
			{
				return this.GetTable<Kategori>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_EkleLog")]
		public int usp_EkleLog([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KULLANICI_ID", DbType="Int")] System.Nullable<int> kULLANICI_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MESAJ", DbType="NText")] string mESAJ, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IP", DbType="NVarChar(20)")] string iP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PAGE", DbType="NVarChar(150)")] string pAGE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STACKTRACE", DbType="NText")] string sTACKTRACE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KAYNAGI", DbType="NText")] string kAYNAGI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OLUSMA_ZAMANI", DbType="DateTime")] System.Nullable<System.DateTime> oLUSMA_ZAMANI)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kULLANICI_ID, mESAJ, iP, pAGE, sTACKTRACE, kAYNAGI, oLUSMA_ZAMANI);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_SiparisIstatistik")]
		public ISingleResult<usp_SiparisIstatistikResult> usp_SiparisIstatistik([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Durum", DbType="NVarChar(30)")] string durum)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), durum);
			return ((ISingleResult<usp_SiparisIstatistikResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_UyariListele")]
		public ISingleResult<usp_UyariListeleResult> usp_UyariListele([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Id", DbType="Int")] System.Nullable<int> user_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_Id);
			return ((ISingleResult<usp_UyariListeleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_UyariEtkilesim")]
		public ISingleResult<usp_UyariEtkilesimResult> usp_UyariEtkilesim([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Id", DbType="Int")] System.Nullable<int> user_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_Id);
			return ((ISingleResult<usp_UyariEtkilesimResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_UserGetir")]
		public ISingleResult<usp_UserGetirResult> usp_UserGetir([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Id", DbType="Int")] System.Nullable<int> user_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_Id);
			return ((ISingleResult<usp_UserGetirResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_UserGetirTumu")]
		public ISingleResult<usp_UserGetirTumuResult> usp_UserGetirTumu()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<usp_UserGetirTumuResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_FirmaTurAdlariGetir")]
		public ISingleResult<usp_FirmaTurAdlariGetirResult> usp_FirmaTurAdlariGetir()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<usp_FirmaTurAdlariGetirResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_FirmaTurEkle")]
		public int usp_FirmaTurEkle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TurAdi", DbType="NVarChar(50)")] string turAdi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), turAdi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_UserEkle")]
		public int usp_UserEkle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KullaniciAdi", DbType="NVarChar(30)")] string kullaniciAdi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sifre", DbType="NVarChar(12)")] string sifre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ad", DbType="NVarChar(20)")] string ad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Soyad", DbType="NVarChar(20)")] string soyad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TcNo", DbType="VarChar(11)")] string tcNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VergiNo", DbType="NVarChar(11)")] string vergiNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefon", DbType="VarChar(16)")] string telefon, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mail", DbType="NVarChar(30)")] string mail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Il", DbType="NVarChar(15)")] string il, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Adres", DbType="NVarChar(80)")] string adres, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirmaTur_Id", DbType="Int")] System.Nullable<int> firmaTur_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Resim", DbType="NVarChar(50)")] string resim, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UyelikBaslangicTarihi", DbType="DateTime")] System.Nullable<System.DateTime> uyelikBaslangicTarihi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UyelikBitisTarihi", DbType="DateTime")] System.Nullable<System.DateTime> uyelikBitisTarihi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kullaniciAdi, sifre, ad, soyad, tcNo, vergiNo, telefon, mail, il, adres, firmaTur_Id, resim, uyelikBaslangicTarihi, uyelikBitisTarihi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_EtkilesimListele")]
		public ISingleResult<usp_EtkilesimListeleResult> usp_EtkilesimListele()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<usp_EtkilesimListeleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_UserSil")]
		public int usp_UserSil([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Id", DbType="Int")] System.Nullable<int> user_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_Id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_UserGuncelle")]
		public int usp_UserGuncelle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Id", DbType="Int")] System.Nullable<int> user_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KullaniciAdi", DbType="NVarChar(30)")] string kullaniciAdi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sifre", DbType="NVarChar(12)")] string sifre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ad", DbType="NVarChar(20)")] string ad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Soyad", DbType="NVarChar(20)")] string soyad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TcNo", DbType="VarChar(11)")] string tcNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VergiNo", DbType="VarChar(11)")] string vergiNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefon", DbType="VarChar(16)")] string telefon, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mail", DbType="NVarChar(30)")] string mail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Il", DbType="NVarChar(15)")] string il, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Adres", DbType="NVarChar(80)")] string adres, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirmaTur_Id", DbType="Int")] System.Nullable<int> firmaTur_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Resim", DbType="NVarChar(50)")] string resim, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UyelikBitisTarihi", DbType="DateTime")] System.Nullable<System.DateTime> uyelikBitisTarihi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_Id, kullaniciAdi, sifre, ad, soyad, tcNo, vergiNo, telefon, mail, il, adres, firmaTur_Id, resim, uyelikBitisTarihi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fnc_UserLogin", IsComposable=true)]
		public System.Nullable<int> fnc_UserLogin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KullaniciAdi", DbType="NVarChar(30)")] string kullaniciAdi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sifre", DbType="NVarChar(12)")] string sifre)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kullaniciAdi, sifre).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_UrunEkleme")]
		public int usp_UrunEkleme([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> user_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Urun_Id", DbType="Int")] System.Nullable<int> urun_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ad", DbType="NVarChar(50)")] string ad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fiyat", DbType="Decimal(18,0)")] System.Nullable<decimal> fiyat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Eklenme_Tarihi", DbType="DateTime")] System.Nullable<System.DateTime> eklenme_Tarihi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OzelNot", DbType="NVarChar(100)")] string ozelNot, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Kategori_Id", DbType="Int")] System.Nullable<int> kategori_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_Id, urun_Id, ad, fiyat, eklenme_Tarihi, ozelNot, kategori_Id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_UrunGuncelle")]
		public int usp_UrunGuncelle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ad", DbType="NVarChar(50)")] string ad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fiyat", DbType="Decimal(18,0)")] System.Nullable<decimal> fiyat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Eklenme_Tarihi", DbType="DateTime")] System.Nullable<System.DateTime> eklenme_Tarihi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OzelNot", DbType="NVarChar(MAX)")] string ozelNot, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Kategori_Id", DbType="Int")] System.Nullable<int> kategori_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Id", DbType="Int")] System.Nullable<int> user_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ad, fiyat, eklenme_Tarihi, ozelNot, kategori_Id, user_Id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_UrunSil")]
		public int usp_UrunSil([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> urun_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> user_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), urun_Id, user_Id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_UrunleriGetir")]
		public ISingleResult<usp_UrunleriGetirResult> usp_UrunleriGetir([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> user_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_Id);
			return ((ISingleResult<usp_UrunleriGetirResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_KategorileriGetir")]
		public ISingleResult<usp_KategorileriGetirResult> usp_KategorileriGetir([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> user_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_Id);
			return ((ISingleResult<usp_KategorileriGetirResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fnc_UserMailKontrol", IsComposable=true)]
		public System.Nullable<int> fnc_UserMailKontrol([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mail", DbType="NVarChar(30)")] string mail)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mail).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Urunler")]
	public partial class Urunler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Urun_Id;
		
		private string _Ad;
		
		private System.Nullable<decimal> _Fiyat;
		
		private System.Nullable<System.DateTime> _Eklenme_Tarihi;
		
		private string _OzelNot;
		
		private System.Nullable<int> _Kategori_Id;
		
		private System.Nullable<int> _User_Id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUrun_IdChanging(int value);
    partial void OnUrun_IdChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnFiyatChanging(System.Nullable<decimal> value);
    partial void OnFiyatChanged();
    partial void OnEklenme_TarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnEklenme_TarihiChanged();
    partial void OnOzelNotChanging(string value);
    partial void OnOzelNotChanged();
    partial void OnKategori_IdChanging(System.Nullable<int> value);
    partial void OnKategori_IdChanged();
    partial void OnUser_IdChanging(System.Nullable<int> value);
    partial void OnUser_IdChanged();
    #endregion
		
		public Urunler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Urun_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Urun_Id
		{
			get
			{
				return this._Urun_Id;
			}
			set
			{
				if ((this._Urun_Id != value))
				{
					this.OnUrun_IdChanging(value);
					this.SendPropertyChanging();
					this._Urun_Id = value;
					this.SendPropertyChanged("Urun_Id");
					this.OnUrun_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50)")]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fiyat", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Fiyat
		{
			get
			{
				return this._Fiyat;
			}
			set
			{
				if ((this._Fiyat != value))
				{
					this.OnFiyatChanging(value);
					this.SendPropertyChanging();
					this._Fiyat = value;
					this.SendPropertyChanged("Fiyat");
					this.OnFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eklenme_Tarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> Eklenme_Tarihi
		{
			get
			{
				return this._Eklenme_Tarihi;
			}
			set
			{
				if ((this._Eklenme_Tarihi != value))
				{
					this.OnEklenme_TarihiChanging(value);
					this.SendPropertyChanging();
					this._Eklenme_Tarihi = value;
					this.SendPropertyChanged("Eklenme_Tarihi");
					this.OnEklenme_TarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OzelNot", DbType="NVarChar(100)")]
		public string OzelNot
		{
			get
			{
				return this._OzelNot;
			}
			set
			{
				if ((this._OzelNot != value))
				{
					this.OnOzelNotChanging(value);
					this.SendPropertyChanging();
					this._OzelNot = value;
					this.SendPropertyChanged("OzelNot");
					this.OnOzelNotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kategori_Id", DbType="Int")]
		public System.Nullable<int> Kategori_Id
		{
			get
			{
				return this._Kategori_Id;
			}
			set
			{
				if ((this._Kategori_Id != value))
				{
					this.OnKategori_IdChanging(value);
					this.SendPropertyChanging();
					this._Kategori_Id = value;
					this.SendPropertyChanged("Kategori_Id");
					this.OnKategori_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="Int")]
		public System.Nullable<int> User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kategori")]
	public partial class Kategori : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Kategori_Id;
		
		private string _Ad;
		
		private System.Nullable<int> _User_Id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKategori_IdChanging(int value);
    partial void OnKategori_IdChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnUser_IdChanging(System.Nullable<int> value);
    partial void OnUser_IdChanged();
    #endregion
		
		public Kategori()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kategori_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Kategori_Id
		{
			get
			{
				return this._Kategori_Id;
			}
			set
			{
				if ((this._Kategori_Id != value))
				{
					this.OnKategori_IdChanging(value);
					this.SendPropertyChanging();
					this._Kategori_Id = value;
					this.SendPropertyChanged("Kategori_Id");
					this.OnKategori_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50)")]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="Int")]
		public System.Nullable<int> User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class usp_SiparisIstatistikResult
	{
		
		private System.Nullable<int> _sayisi;
		
		public usp_SiparisIstatistikResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sayisi", DbType="Int")]
		public System.Nullable<int> sayisi
		{
			get
			{
				return this._sayisi;
			}
			set
			{
				if ((this._sayisi != value))
				{
					this._sayisi = value;
				}
			}
		}
	}
	
	public partial class usp_UyariListeleResult
	{
		
		private string _Tur;
		
		private System.Nullable<System.DateTime> _Tarih;
		
		private string _adSoyad;
		
		public usp_UyariListeleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tur", DbType="NVarChar(35)")]
		public string Tur
		{
			get
			{
				return this._Tur;
			}
			set
			{
				if ((this._Tur != value))
				{
					this._Tur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this._Tarih = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adSoyad", DbType="NVarChar(41)")]
		public string adSoyad
		{
			get
			{
				return this._adSoyad;
			}
			set
			{
				if ((this._adSoyad != value))
				{
					this._adSoyad = value;
				}
			}
		}
	}
	
	public partial class usp_UyariEtkilesimResult
	{
		
		private string _Tur;
		
		private System.Nullable<System.DateTime> _Tarih;
		
		private string _adSoyad;
		
		public usp_UyariEtkilesimResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tur", DbType="NVarChar(35)")]
		public string Tur
		{
			get
			{
				return this._Tur;
			}
			set
			{
				if ((this._Tur != value))
				{
					this._Tur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this._Tarih = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adSoyad", DbType="NVarChar(41)")]
		public string adSoyad
		{
			get
			{
				return this._adSoyad;
			}
			set
			{
				if ((this._adSoyad != value))
				{
					this._adSoyad = value;
				}
			}
		}
	}
	
	public partial class usp_UserGetirResult
	{
		
		private int _User_Id;
		
		private string _KullaniciAdi;
		
		private string _Sifre;
		
		private string _Ad;
		
		private string _Soyad;
		
		private string _TcNo;
		
		private string _VergiNo;
		
		private string _Telefon;
		
		private string _Mail;
		
		private string _Il;
		
		private string _Adres;
		
		private System.Nullable<int> _FirmaTur_Id;
		
		private string _Resim;
		
		private System.Nullable<System.DateTime> _UyelikBaslangicTarihi;
		
		private System.Nullable<System.DateTime> _UyelikBitisTarihi;
		
		public usp_UserGetirResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="Int NOT NULL")]
		public int User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this._User_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciAdi", DbType="NVarChar(30)")]
		public string KullaniciAdi
		{
			get
			{
				return this._KullaniciAdi;
			}
			set
			{
				if ((this._KullaniciAdi != value))
				{
					this._KullaniciAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(12)")]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this._Sifre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(20)")]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this._Ad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyad", DbType="NVarChar(20)")]
		public string Soyad
		{
			get
			{
				return this._Soyad;
			}
			set
			{
				if ((this._Soyad != value))
				{
					this._Soyad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TcNo", DbType="VarChar(11)")]
		public string TcNo
		{
			get
			{
				return this._TcNo;
			}
			set
			{
				if ((this._TcNo != value))
				{
					this._TcNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VergiNo", DbType="VarChar(11)")]
		public string VergiNo
		{
			get
			{
				return this._VergiNo;
			}
			set
			{
				if ((this._VergiNo != value))
				{
					this._VergiNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="VarChar(16)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this._Telefon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="NVarChar(30)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this._Mail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Il", DbType="NVarChar(15)")]
		public string Il
		{
			get
			{
				return this._Il;
			}
			set
			{
				if ((this._Il != value))
				{
					this._Il = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(80)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this._Adres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirmaTur_Id", DbType="Int")]
		public System.Nullable<int> FirmaTur_Id
		{
			get
			{
				return this._FirmaTur_Id;
			}
			set
			{
				if ((this._FirmaTur_Id != value))
				{
					this._FirmaTur_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim", DbType="NVarChar(50)")]
		public string Resim
		{
			get
			{
				return this._Resim;
			}
			set
			{
				if ((this._Resim != value))
				{
					this._Resim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyelikBaslangicTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> UyelikBaslangicTarihi
		{
			get
			{
				return this._UyelikBaslangicTarihi;
			}
			set
			{
				if ((this._UyelikBaslangicTarihi != value))
				{
					this._UyelikBaslangicTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyelikBitisTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> UyelikBitisTarihi
		{
			get
			{
				return this._UyelikBitisTarihi;
			}
			set
			{
				if ((this._UyelikBitisTarihi != value))
				{
					this._UyelikBitisTarihi = value;
				}
			}
		}
	}
	
	public partial class usp_UserGetirTumuResult
	{
		
		private int _User_Id;
		
		private string _KullaniciAdi;
		
		private string _Sifre;
		
		private string _Ad;
		
		private string _Soyad;
		
		private string _TcNo;
		
		private string _VergiNo;
		
		private string _Telefon;
		
		private string _Mail;
		
		private string _Il;
		
		private string _Adres;
		
		private string _TurAdi;
		
		private string _Resim;
		
		private System.Nullable<System.DateTime> _UyelikBaslangicTarihi;
		
		private System.Nullable<System.DateTime> _UyelikBitisTarihi;
		
		public usp_UserGetirTumuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="Int NOT NULL")]
		public int User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this._User_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciAdi", DbType="NVarChar(30)")]
		public string KullaniciAdi
		{
			get
			{
				return this._KullaniciAdi;
			}
			set
			{
				if ((this._KullaniciAdi != value))
				{
					this._KullaniciAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(12)")]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this._Sifre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(20)")]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this._Ad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyad", DbType="NVarChar(20)")]
		public string Soyad
		{
			get
			{
				return this._Soyad;
			}
			set
			{
				if ((this._Soyad != value))
				{
					this._Soyad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TcNo", DbType="VarChar(11)")]
		public string TcNo
		{
			get
			{
				return this._TcNo;
			}
			set
			{
				if ((this._TcNo != value))
				{
					this._TcNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VergiNo", DbType="VarChar(11)")]
		public string VergiNo
		{
			get
			{
				return this._VergiNo;
			}
			set
			{
				if ((this._VergiNo != value))
				{
					this._VergiNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="VarChar(16)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this._Telefon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="NVarChar(30)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this._Mail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Il", DbType="NVarChar(15)")]
		public string Il
		{
			get
			{
				return this._Il;
			}
			set
			{
				if ((this._Il != value))
				{
					this._Il = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(80)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this._Adres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TurAdi", DbType="NVarChar(50)")]
		public string TurAdi
		{
			get
			{
				return this._TurAdi;
			}
			set
			{
				if ((this._TurAdi != value))
				{
					this._TurAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim", DbType="NVarChar(50)")]
		public string Resim
		{
			get
			{
				return this._Resim;
			}
			set
			{
				if ((this._Resim != value))
				{
					this._Resim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyelikBaslangicTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> UyelikBaslangicTarihi
		{
			get
			{
				return this._UyelikBaslangicTarihi;
			}
			set
			{
				if ((this._UyelikBaslangicTarihi != value))
				{
					this._UyelikBaslangicTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyelikBitisTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> UyelikBitisTarihi
		{
			get
			{
				return this._UyelikBitisTarihi;
			}
			set
			{
				if ((this._UyelikBitisTarihi != value))
				{
					this._UyelikBitisTarihi = value;
				}
			}
		}
	}
	
	public partial class usp_FirmaTurAdlariGetirResult
	{
		
		private int _FirmaTur_Id;
		
		private string _TurAdi;
		
		public usp_FirmaTurAdlariGetirResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirmaTur_Id", DbType="Int NOT NULL")]
		public int FirmaTur_Id
		{
			get
			{
				return this._FirmaTur_Id;
			}
			set
			{
				if ((this._FirmaTur_Id != value))
				{
					this._FirmaTur_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TurAdi", DbType="NVarChar(50)")]
		public string TurAdi
		{
			get
			{
				return this._TurAdi;
			}
			set
			{
				if ((this._TurAdi != value))
				{
					this._TurAdi = value;
				}
			}
		}
	}
	
	public partial class usp_EtkilesimListeleResult
	{
		
		private int _User_Id;
		
		private string _KullaniciAdi;
		
		private string _Il;
		
		private string _Telefon;
		
		private string _Resim;
		
		private string _TurAdi;
		
		public usp_EtkilesimListeleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="Int NOT NULL")]
		public int User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this._User_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciAdi", DbType="NVarChar(30)")]
		public string KullaniciAdi
		{
			get
			{
				return this._KullaniciAdi;
			}
			set
			{
				if ((this._KullaniciAdi != value))
				{
					this._KullaniciAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Il", DbType="NVarChar(15)")]
		public string Il
		{
			get
			{
				return this._Il;
			}
			set
			{
				if ((this._Il != value))
				{
					this._Il = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="VarChar(16)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this._Telefon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim", DbType="NVarChar(50)")]
		public string Resim
		{
			get
			{
				return this._Resim;
			}
			set
			{
				if ((this._Resim != value))
				{
					this._Resim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TurAdi", DbType="NVarChar(50)")]
		public string TurAdi
		{
			get
			{
				return this._TurAdi;
			}
			set
			{
				if ((this._TurAdi != value))
				{
					this._TurAdi = value;
				}
			}
		}
	}
	
	public partial class usp_UrunleriGetirResult
	{
		
		private int _Urun_Id;
		
		private string _Ad;
		
		private System.Nullable<decimal> _Fiyat;
		
		private System.Nullable<System.DateTime> _Eklenme_Tarihi;
		
		private string _kad;
		
		private int _Kategori_Id;
		
		private string _OzelNot;
		
		public usp_UrunleriGetirResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Urun_Id", DbType="Int NOT NULL")]
		public int Urun_Id
		{
			get
			{
				return this._Urun_Id;
			}
			set
			{
				if ((this._Urun_Id != value))
				{
					this._Urun_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50)")]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this._Ad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fiyat", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Fiyat
		{
			get
			{
				return this._Fiyat;
			}
			set
			{
				if ((this._Fiyat != value))
				{
					this._Fiyat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eklenme_Tarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> Eklenme_Tarihi
		{
			get
			{
				return this._Eklenme_Tarihi;
			}
			set
			{
				if ((this._Eklenme_Tarihi != value))
				{
					this._Eklenme_Tarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kad", DbType="NVarChar(50)")]
		public string kad
		{
			get
			{
				return this._kad;
			}
			set
			{
				if ((this._kad != value))
				{
					this._kad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kategori_Id", DbType="Int NOT NULL")]
		public int Kategori_Id
		{
			get
			{
				return this._Kategori_Id;
			}
			set
			{
				if ((this._Kategori_Id != value))
				{
					this._Kategori_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OzelNot", DbType="NVarChar(100)")]
		public string OzelNot
		{
			get
			{
				return this._OzelNot;
			}
			set
			{
				if ((this._OzelNot != value))
				{
					this._OzelNot = value;
				}
			}
		}
	}
	
	public partial class usp_KategorileriGetirResult
	{
		
		private int _Kategori_Id;
		
		private string _Ad;
		
		public usp_KategorileriGetirResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kategori_Id", DbType="Int NOT NULL")]
		public int Kategori_Id
		{
			get
			{
				return this._Kategori_Id;
			}
			set
			{
				if ((this._Kategori_Id != value))
				{
					this._Kategori_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50)")]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this._Ad = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
